<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(XcacivTargetFrameworks)</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Xcaciv.Command.Core\Xcaciv.Command.Core.csproj" />
    <ProjectReference Include="..\..\Xcaciv.Command.Interface\Xcaciv.Command.Interface.csproj" />
    <ProjectReference Include="..\..\Xcaciv.Command\Xcaciv.Command.csproj" />
  </ItemGroup>
</Project>
