# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Debug Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: src\Xcaciv.Command\Xcaciv.Command.sln                         # your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: src\Xcaciv.Command\**\*Tests.csproj  # path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Net_Project_Directory: Xcaciv.Command    # the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Net_Project_Path: src\Xcaciv.Command\Xcaciv.Command\Xcaciv.Command.csproj                   # path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name
    - name: Debug Build
      run: dotnet build $env:Solution_Name --no-restore --configuration Debug
    - name: Test
      run: dotnet test $env:Solution_Name --no-build --verbosity normal
    - name: Clean Build
      run: dotnet clean $env:Solution_Name
